Add column movement UI
spine-examples/kanban pull request #137
Opened 2022-10-31 11:51 UTC by tripolkaandrey

This PR adds UI for column movement. 
Here is a demo:
![demo](https://user-images.githubusercontent.com/54888768/199001467-a5f54b06-8d38-4109-ae34-ef5a889b7488.gif)
Also, subscriptions to events are removed in favour of subscribing to changes in the `Board` projection's state.

2022-10-31 12:24 UTC, armiol requested changes
@tripolkaandrey please see my comments.

Other than those, LGTM.

2022-10-31 12:24 UTC, armiol commented on web/client-js/src/store/board/actions/command/move-column-action.ts
> +> {
Can we please leave the closing bracket on the previous line?

2022-10-31 12:24 UTC, armiol commented on web/client-js/src/views/BoardView.vue
> +      >
Can we please have the corresponding bracket of a tag on the same line as the last significant text?

This changeset illustrates the poor readability with the standalone `>`, `/>`, etc, bouncing all over the places.

2022-10-31 12:54 UTC, armiol approved these changes

2022-10-31 12:55 UTC, merged

2022-11-05 17:48 UTC, alexander-yevsyukov commented
@tripolkaandrey,  @armiol, what if we start applying [Aqua](https://www.jetbrains.com/aqua/) to our example projects?